- name: Ruleset for URL check source test
  hosts: all
  sources:
    - name: check site
      ansible.eda.url_check:
        urls:
         - https://www.wikipedia.org
        delay: 10
  rules:
    - name: Check if endpoint is responding
      condition: event.url_check.status == "up"
      action:
        run_module:
          name: ansible.builtin.debug
          module_args:
            msg: SUCCESS
