---
name: awx-project-update

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Set project name or id'
        required: true
        default: 'demo'

jobs:
  awx:
    runs-on: ubuntu-latest
    steps:
      - name: "Update AWX project"
        id: project_update
        uses: fitbeard/action-trigger-awx@07f735a6271508b296ddffbeaa64e67eac314bc8
        with:
          controller_host: ${{ secrets.CONTROLLER_HOST }}
          controller_oauth_token: ${{ secrets.CONTROLLER_OAUTH_TOKEN }}
          controller_verify_ssl: false
          resource_type: project
          resource_name: ${{ github.event.inputs.project }}

      - name: Output AWX job id
        run: |
          echo ${{ steps.project_update.outputs.job_id }}
